config/routes.rb
Invest::Application.routes.draw do
  match 'demo' => 'demo#index'

  resources :angels do
    member do
      get 'csv_import'
    end
  end

  get "home/index"

    match 'invest/:key' => 'angels#show'
    match 'angels/import' => 'angels#csv_import'

  root :to => 'home#index'

end

app/models/angel.rb
class Angel < ActiveRecord::Base
end

app/controllers/angels_controller.rb
class AngelsController < ApplicationController
  # GET /angels
  # GET /angels.json
  def index
    @angels = Angel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @angels }
    end
  end

  # GET /angels/1
  # GET /angels/1.json
  def show
    @angel = Angel.where("key = ?", params[:key]).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @angel }
    end
  end

  # GET /angels/new
  # GET /angels/new.json
  def new
    @angel = Angel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @angel }
    end
  end

  # GET /angels/1/edit
  def edit
    @angel = Angel.find(params[:id])
  end

  # POST /angels
  # POST /angels.json
  def create
    @angel = Angel.new(params[:angel])

    respond_to do |format|
      if @angel.save
        format.html { redirect_to :action => 'show', :key => @angel.key, notice: 'Angel was successfully created.' }
        format.json { render json: @angel, status: :created, location: @angel }
      else
        format.html { render action: "new" }
        format.json { render json: @angel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /angels/1
  # PUT /angels/1.json
  def update
    @angel = Angel.find(params[:id])

    respond_to do |format|
      if @angel.update_attributes(params[:angel])
        format.html { redirect_to @angel, notice: 'Angel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @angel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /angels/1
  # DELETE /angels/1.json
  def destroy
    @angel = Angel.find(params[:id])
    @angel.destroy

    respond_to do |format|
      format.html { redirect_to angels_url }
      format.json { head :no_content }
    end
  end

#script to upload CSV files of angels
require 'csv'
  def csv_import
     CSV.foreach("public/newangels.txt", :quote_char => '"', :col_sep =>',', :row_sep =>:auto) do |row|
       Angel.create!(:key => row[0], :fullname => row[1], :company => row[2], :custom => row[3])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/angels_helper.rb
module AngelsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/angels/_form.html.erb
<%= form_for(@angel) do |f| %>
  <% if @angel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@angel.errors.count, "error") %> prohibited this angel from being saved:</h2>

      <ul>
      <% @angel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :fullname %><br />
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :custom %><br />
    <%= f.text_area :custom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/angels/_uploadform.html.erb
 <% form_for(@uploaded, :url=>{:controller=>"angels", :action=>"csv_import"}, :html => { :multipart => true }) do |f| %>
<%= f.error_messages %>
 <table>
   <tr>

     <td >
	 <%= f.label :file %><br />
     <%= f.file_field :file %>
     </td>
   </tr>
   <tr>
     <td colspan='2'>
       <%= f.submit 'csv_import' %>
     </td>
   </tr>
 </table>
<% end %>

app/views/angels/edit.html.erb
<h1>Editing angel</h1>

<%= render 'form' %>

<%= link_to 'Show', @angel %> |
<%= link_to 'Back', angels_path %>

app/views/angels/index.html.erb
<h1>Listing angels</h1>

<table>
  <tr>
    <th>Key</th>
    <th>Fullname</th>
    <th>Company</th>
    <th>Custom</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @angels.each do |angel| %>
  <tr>
    <td><%= angel.key %></td>
    <td><%= angel.fullname %></td>
    <td><%= angel.company %></td>
    <td><%= angel.custom %></td>
    <td><%= link_to 'Show', angel %></td>
    <td><%= link_to 'Edit', edit_angel_path(angel) %></td>
    <td><%= link_to 'Destroy', angel, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Angel', new_angel_path %>

app/views/angels/new.html.erb
<h1>New angel</h1>

<%= render 'form' %>

<%= link_to 'Back', angels_path %>

<%= form_tag('import') do %>
  <%= file_field_tag :file %>
  <%= submit_tag %>
<% end %>

app/views/angels/show.html.erb
<body background=#EBDDE2>

<br><br>

<div style="text-align:center"><font size="6"><%= @angel.fullname %>, thanks for stopping by! <br><br>
	
	
	<%= @angel.company %> should consider investing in <b><font color="#ff9900">Let's Get Popcorn</font></b>!</font></div><div style="text-align:center"><i><font size="5">(and don't worry, i google myself too...)</font></i></div><div style="text-align:center"><font size="6"><br /></font></div></div></div>
	
	<table cellspacing="0"><tr>
		<td width=50% valign=top><center><font size="3"><Br><br><br><u>Our video pitch:</u> (sometimes takes a second...)</font><br /><iframe width="425" height="355" src="//www.youtube.com/embed/7p-UQAeuLnM?rel=0" frameborder="0" allowFullScreen="true"></iframe><br /><font size="5"><br /></font><font size="5">Pitch Deck: </font><a href="http://bit.ly/A2wBIh" style="font-size:x-large" target="_blank">PPT</a><span style="font-size:x-large"> | </span><a href="http://bit.ly/zXlWUr" style="font-size:x-large" target="_blank">PDF</a></div><div><font size="5"><br /></font></div><div><u><font size="5">Contact</font></u></div><div><font size="4">veesh@rockingchairllc.com | 412-418-4201</font></div><div><a href="http://angel.co/let-s-get-popcorn"><font size="4">http://angel.co/let-s-get-popcorn</font></a></div><div><br /></div></div></div></center></td>
		<td><div style="text-align:left"><u><font size="3"><br><br><br>Even if you're not <%= @angel.fullname %>, we're seeking our first $50k in seed funding, please share your thoughts below...</font></u></div><div style="text-align:center"><font size="5"><div><div><div class="sites-embed-border-off sites-embed sites-embed-full-width" style="width:100%;"><div><iframe src="http://spreadsheets.google.com/spreadsheet/embeddedform?bc=transparent&amp;f=Arial%252C%2BVerdana%252C%2Bsans-serif&amp;formkey=dElvNDlPZXV1VnB5S3l2TWV6LTZUUmc6MQ&amp;hl=en&amp;htc=%2523666666&amp;lc=%2523c21d0c&amp;pli=1&amp;tc=%2523000000&amp;ttl=0" width="100%" height="600" title="Google Spreadsheet Form" allowtransparency="true" frameborder="0" marginheight="0" marginwidth="0" id="965849954"> </iframe>
</body>
</html>

app/views/angels/show2.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Key:</b>
  <%= @angel.key %>
</p>

<p>
  <b>Fullname:</b>
  <%= @angel.fullname %>
</p>

<p>
  <b>Company:</b>
  <%= @angel.company %>
</p>

<p>
  <b>Custom:</b>
  <%= @angel.custom %>
</p>


Let's Get Popcorn is a <a href='http://www.rockingchairllc.com'>RockingChair LLC</a> brand.

app/views/demo/index.html.erb
Walkthrough of site:
<br>
<iframe width="1280" height="720" src="http://www.youtube.com/embed/HIaT_a3uF_o" frameborder="0" allowfullscreen></iframe>

app/views/home/index.html.erb
<body bgcolor="666666"></body>

<div rel="1ZKD4NGD" class="lrdiscoverwidget" data-logo="on" data-background="on" data-share-url="www.letsgetpopcorn.com" data-css=""></div><script type="text/javascript" src="http://launchrock-ignition.s3.amazonaws.com/ignition.1.1.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Invest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>